services:
  # ── Service 1: PostgreSQL database ──────────────
  db:
    image: postgres:15
    container_name: blooddonor_db
    environment:
      POSTGRES_DB: blooddonor
      POSTGRES_USER: postgres
      POSTGRES_PASSWORD: 59F21a0463@123AP40BX3122
    ports:
      - "5432:5432"
    volumes:
      - postgres_data:/var/lib/postgresql/data
    healthcheck:
      test: ["CMD-SHELL", "pg_isready -U postgres"]
      interval: 5s
      timeout: 5s
      retries: 5

  # ── Service 2: Flask app ─────────────────────────
  web:
    image: fayazshaik15f21a0463/blood-donor-app:latest
    container_name: blooddonor_web
    expose:
      - "5000"                    # ← CHANGED from ports to expose
    environment:
      DB_HOST: db
      DB_PORT: 5432
      DB_NAME: blooddonor
      DB_USER: postgres
      DB_PASSWORD: 59F21a0463@123AP40BX3122
      SECRET_KEY: blooddonor2024
    depends_on:
      db:
        condition: service_healthy

  # ── Service 3: Nginx ─────────────────────────────
  nginx:
    image: nginx:latest
    container_name: blooddonor_nginx
    ports:
      - "80:80"                   # ← port 80 exposed to world
    volumes:
      - ./nginx.conf:/etc/nginx/nginx.conf:ro
    depends_on:
      - web

# ── Volume ──────────────────────────────────────
volumes:
  postgres_data:
